### ISSUE TITLE
Reference test_0016_meta_data_url. Apply JSON rfc8785 canonicalization ?

### ISSUE THREAD

**Issue by branciard** [branciard/iscc-core-ts#2]
Data url in this case is "data:application/json;charset=utf-8;base64,eyJzb21lIjogIm9iamVjdCJ9"

"eyJzb21lIjogIm9iamVjdCJ9" is decoded  as : 
``` 
{"some": "object"}  // with space
``` 

eyJzb21lIjoib2JqZWN0In0= is decoded  as : 
``` 
{"some":"object"}  // without space
``` 

JSON rfc8785 canonicalization remove space :  
``` 
{"some": "object"}  // with space
{"some":"object"}  // without space
``` 
Black3 hash result will be different and final meta code too :
``` 
 BLAKE3 Hashing {"some":"object"} =>111d3302b0605ec558c390ee013ae89ec6eea68ad2317a8b2de3f4169afeb2ca
 BLAKE3 Hashing {"some": "object"}=>796fdfd4ba8db1a63a1ad1377fa735cad99a10ff08bc655a7095d6508e815a0f
``` 

Do we have to apply JSON rfc8785 canonicalization on all JSON data before created BLAKE3 hash of it ?
 
[Test link](https://github.com/branciard/iscc-core-ts/blob/main/src/data.test.ts#L273)

**Comment by titusz** [comment]
Yes, if we want reproducibility we need to agree on a deterministic serialization before hashing.

**Comment by branciard** [comment]
Conform to spec : https://ieps.iscc.codes/iep-0002/#43-meta-element  
 - Canonicalization before being wrapped in a Data-URL
 - Data URL to a raw bitstream without further interpretation.
